import type { CanonicalSnp } from "./types";

export const CANONICAL_SNPS: CanonicalSnp[] = [
  // ================ TRAITS / APPEARANCE ================
  {
    rsid: "rs12913832",
    gene: "HERC2",
    geneFullName: "HERC2 — HECT and RLD domain containing E3 ubiquitin protein ligase 2",
    chrom: "15",
    position: 28365618,
    category: "trait",
    title: "Cor dos olhos — o SNP do olho azul",
    shortDesc: "Variante reguladora do OCA2 — o maior preditor único de olhos azuis em europeus.",
    longDesc: "Este SNP localizado em um íntron do gene HERC2 atua como um elemento regulador (enhancer) do gene vizinho OCA2. Quase todos os indivíduos com olhos azuis em ancestralidade europeia carregam o alelo derivado G/G neste sítio — rastreando a uma única mutação fundadora há ~6.000–10.000 anos. Estima-se que o SNP explique ~74% da variância de cor de íris em europeus.",
    mechanism: "O alelo ancestral A permite ligação do fator transcricional HLTF, que aumenta expressão de OCA2. OCA2 regula a produção de melanina nos melanócitos da íris. O alelo derivado G reduz essa expressão → menos melanina → íris azul.",
    interpretations: {
      AA: "Olhos castanhos muito prováveis (alelo ancestral homozigoto).",
      AG: "Fenótipo intermediário — verdes, avelã ou castanho-claro.",
      GG: "Olhos azuis altamente prováveis (~85% de probabilidade em europeus).",
    },
    references: [
      { label: "Eiberg H, et al. Blue eye color in humans... Hum Genet 2008", pmid: "18172690" },
      { label: "Sturm RA, et al. AJHG 2008", pmid: "18252222" },
      { label: "SNPedia: rs12913832", url: "https://www.snpedia.com/index.php/Rs12913832" },
    ],
    populationNotes: "Frequência do alelo G: ~80% em escandinavos, ~20% em populações do sul da Europa, <1% na maioria das populações africanas e asiáticas.",
    actionable: "Nenhuma ação clínica — traço fenotípico sem implicação de saúde.",
    tags: ["olhos", "pigmentação", "europeu"],
  },
  {
    rsid: "rs1805007",
    gene: "MC1R",
    geneFullName: "MC1R — Melanocortin 1 Receptor (variante R151C)",
    chrom: "16",
    position: 89986117,
    category: "trait",
    title: "MC1R R151C — cabelo ruivo e UV",
    shortDesc: "Uma das três variantes 'red hair color' (RHC) clássicas do MC1R.",
    longDesc: "MC1R é o receptor que regula a decisão dos melanócitos entre produzir eumelanina (marrom/preta, fotoprotetora) e feomelanina (amarela/vermelha, pouco fotoprotetora). Variantes de perda de função como R151C deslocam o balanço para feomelanina, resultando em cabelo ruivo, pele muito clara, sardas e risco aumentado de melanoma e carcinoma basocelular independente de exposição solar.",
    mechanism: "R151C (rs1805007), R160W (rs1805008) e D294H (rs1805009) são as 'RHC strong alleles'. Reduzem drasticamente a sinalização cAMP induzida por α-MSH. Ruivos homozigotos típicos carregam duas dessas variantes (em qualquer combinação).",
    interpretations: {
      CC: "Sem R151C — fenótipo depende de outras variantes MC1R.",
      CT: "Heterozigoto — pele clara, tendência a sardas, risco modesto de melanoma elevado.",
      TT: "Homozigoto — cabelo ruivo muito provável em contexto europeu, pele altamente sensível ao sol.",
    },
    clinicalSignificance: "vus",
    references: [
      { label: "Valverde P, et al. Nat Genet 1995", pmid: "7581459" },
      { label: "Duffy DL, et al. AJHG 2004", pmid: "14695997" },
      { label: "OMIM 155555", url: "https://omim.org/entry/155555" },
    ],
    populationNotes: "Frequência do T: ~8% em europeus do norte, raríssimo em populações não-europeias.",
    actionable: "Protetor solar FPS alto, screening dermatológico anual se homozigoto ou heterozigoto composto com outras RHC.",
    tags: ["ruivo", "melanoma", "UV"],
  },
  {
    rsid: "rs1426654",
    gene: "SLC24A5",
    geneFullName: "SLC24A5 — Solute Carrier Family 24 Member 5",
    chrom: "15",
    position: 48426484,
    category: "trait",
    title: "SLC24A5 — pigmentação global de pele",
    shortDesc: "Variante fixada em populações europeias, uma das maiores de efeito único em pigmentação humana.",
    longDesc: "A variante A111T (rs1426654) explica 25-38% da diferença de pigmentação entre europeus e africanos. Está praticamente fixada em europeus (~99%) mas é rara em africanos e do leste asiático. Descoberta originalmente em peixes-zebra ('golden mutation').",
    mechanism: "SLC24A5 é um trocador Na⁺/Ca²⁺/K⁺ na membrana do melanossomo. A variante A111T reduz atividade, diminuindo a maturação de melanossomos → menos eumelanina → pele mais clara.",
    interpretations: {
      AA: "Alelo derivado (Thr) homozigoto — pigmentação mais clara (padrão europeu).",
      AG: "Heterozigoto — pigmentação intermediária, frequente em sul-asiáticos e miscigenados.",
      GG: "Alelo ancestral (Ala) — pigmentação mais escura, padrão africano/leste-asiático.",
    },
    references: [
      { label: "Lamason RL, et al. SLC24A5... Science 2005", pmid: "16357253" },
      { label: "Norton HL, et al. MBE 2007", pmid: "17182896" },
    ],
    populationNotes: "Frequência do A: ~99% europeus, ~50% sul-asiáticos, <10% leste-asiáticos, ~7% africanos (variantes distintas contribuem em cada região).",
    tags: ["pele", "pigmentação"],
  },
  {
    rsid: "rs17822931",
    gene: "ABCC11",
    geneFullName: "ABCC11 — ATP Binding Cassette Subfamily C Member 11",
    chrom: "16",
    position: 48258198,
    category: "trait",
    title: "ABCC11 — cera de ouvido seca e odor axilar",
    shortDesc: "Uma das variantes fenotípicas mais dramáticas do genoma humano — muda cera de ouvido de úmida para seca.",
    longDesc: "O SNP G180R no ABCC11 determina simultaneamente o tipo de cera de ouvido (úmida vs seca) e o odor axilar. O alelo T (seco) provoca degradação rápida da proteína no retículo endoplasmático, eliminando o transportador das glândulas apócrinas. Resultado: cera seca e flocosa, e pouco/nenhum odor axilar — porque os precursores de odor (mercapto-hexanol, androstenonas) não são secretados.",
    mechanism: "ABCC11 (MRP8) transporta conjugados precursores que bactérias axilares convertem em compostos voláteis. Sem ele → matéria-prima do odor ausente. O alelo T também reduz colostro em mães lactantes (estudos coreanos).",
    interpretations: {
      CC: "Cera úmida e pegajosa (amarelo-marrom), odor axilar normal/elevado.",
      CT: "Heterozigoto — cera úmida (alelo C é dominante), odor normal.",
      TT: "Cera seca e cinza/branca, pouco ou nenhum odor axilar. Não precisa usar desodorante em muitos casos.",
    },
    references: [
      { label: "Yoshiura K, et al. Nat Genet 2006", pmid: "16444273" },
      { label: "Martin A, et al. J Invest Dermatol 2010", pmid: "19812594" },
    ],
    populationNotes: "Frequência do T: ~80-95% em leste-asiáticos (chineses, coreanos, japoneses), ~30-50% em ameríndios, <3% em europeus e africanos.",
    tags: ["odor", "cerume"],
  },
  {
    rsid: "rs713598",
    gene: "TAS2R38",
    geneFullName: "TAS2R38 — Taste 2 Receptor Member 38 (P49A)",
    chrom: "7",
    position: 141672604,
    category: "trait",
    title: "TAS2R38 — sensibilidade ao amargo (PTC)",
    shortDesc: "Define se você é 'taster' ou 'non-taster' de feniltiocarbamida e compostos amargos similares.",
    longDesc: "TAS2R38 é um receptor de sabor amargo em células gustativas. Três SNPs (P49A, A262V, V296I) definem dois haplótipos principais: PAV (taster) e AVI (non-taster). Tasters detectam PTC e propiltiouracil em concentrações baixíssimas, e geralmente acham mais amargos vegetais crucíferos (brócolis, couve de bruxelas, rúcula), café preto e tônica.",
    mechanism: "PAV se acopla eficientemente a compostos tiocarbamídicos. AVI tem afinidade reduzida. O fenótipo afeta escolha alimentar — non-tasters tendem a consumir mais vegetais amargos e bebidas alcoólicas amargas.",
    interpretations: {
      CC: "Taster provável — sensibilidade aumentada a amargos.",
      CG: "Taster intermediário.",
      GG: "Non-taster provável — pode nem sentir PTC.",
    },
    references: [
      { label: "Kim UK, et al. Science 2003", pmid: "12595602" },
      { label: "Duffy VB, et al. Alcohol Clin Exp Res 2004", pmid: "15597093" },
    ],
    populationNotes: "Cerca de 70% dos europeus e 85% dos africanos são tasters. A proporção no Brasil é próxima aos europeus.",
    actionable: "Não há ação clínica. Pode explicar aversões alimentares persistentes.",
    tags: ["paladar", "dieta"],
  },
  {
    rsid: "rs72921001",
    gene: "OR6A2",
    geneFullName: "OR6A2 — Olfactory Receptor Family 6 Subfamily A Member 2",
    chrom: "11",
    position: 6914447,
    category: "trait",
    title: "OR6A2 — coentro com gosto de sabão",
    shortDesc: "Variante em receptor olfativo associada à percepção de coentro como sabonete.",
    longDesc: "A aversão ao coentro é altamente hereditária (~50% em gêmeos). O GWAS da 23andMe encontrou rs72921001 num cluster de receptores olfativos no cromossomo 11 como o principal sinal genético. OR6A2 é particularmente sensível aos aldeídos E-2-decenal e E-2-dodecenal — também presentes em sabões.",
    interpretations: {
      AA: "Alelo associado a sentir coentro com gosto de sabão.",
      AC: "Intermediário.",
      CC: "Coentro geralmente agradável.",
    },
    references: [
      { label: "Eriksson N, et al. Flavour 2012 (23andMe)", url: "https://flavourjournal.biomedcentral.com/articles/10.1186/2044-7248-1-22" },
    ],
    tags: ["olfato", "dieta"],
  },
  {
    rsid: "rs1800414",
    gene: "OCA2",
    geneFullName: "OCA2 — OCA2 Melanosomal Transmembrane Protein (H615R)",
    chrom: "15",
    position: 28197037,
    category: "trait",
    title: "OCA2 H615R — pigmentação leste-asiática",
    shortDesc: "Variante praticamente exclusiva do leste-asiático, contribui para pele mais clara.",
    longDesc: "Enquanto rs1426654 explica pigmentação clara em europeus, esta variante (H615R) é o equivalente funcional em chineses, coreanos e japoneses. Frequência ~60% no leste-asiático, virtualmente zero em europeus e africanos — exemplo clássico de seleção convergente.",
    interpretations: {
      AA: "Alelo ancestral — pigmentação mais escura.",
      AG: "Heterozigoto.",
      GG: "Variante derivada — pigmentação mais clara (padrão leste-asiático).",
    },
    references: [
      { label: "Eaton K, et al. PLoS ONE 2015", pmid: "26445240" },
    ],
    tags: ["pele", "pigmentação", "asiático"],
  },

  // ================ HEALTH ================
  {
    rsid: "rs429358",
    gene: "APOE",
    geneFullName: "APOE — Apolipoprotein E (variante ε4/ε3)",
    chrom: "19",
    position: 45411941,
    category: "health",
    title: "APOE ε4 — o maior fator genético comum de risco para Alzheimer",
    shortDesc: "Combinado com rs7412 define o haplótipo APOE (ε2/ε3/ε4). ε4 é o maior preditor genético comum de Alzheimer tardio.",
    longDesc: "APOE tem três isoformas (ε2, ε3, ε4) definidas pelos dois SNPs rs429358 e rs7412. A isoforma ε4 (alelo C aqui, T em rs7412) interfere na clearance de β-amiloide cerebral, aumentando risco de Alzheimer ~3× em heterozigotos e ~12-15× em homozigotos vs ε3/ε3. Também associada a risco CV aumentado e pior desfecho após TBI. ε2 (T em rs429358, T em rs7412) é protetor contra Alzheimer mas aumenta risco de hiperlipoproteinemia III.",
    mechanism: "A apoE é a principal apolipoproteína cerebral. A isoforma ε4 (Arg112, Arg158) tem pior ligação a receptores LRP1/LDLR para remoção de Aβ e pior modulação de inflamação via microglia. Duas cópias de ε4 antecipam Alzheimer ~10-15 anos vs ε3/ε3.",
    interpretations: {
      TT: "Não carrega ε4 neste SNP (genótipo ε2/ε2, ε2/ε3 ou ε3/ε3 dependendo de rs7412).",
      CT: "Heterozigoto — portador de UMA cópia ε4 se rs7412=CC (ε3/ε4 mais comum). Risco Alzheimer ~3×.",
      CC: "Homozigoto — DUAS cópias ε4 se rs7412=CC (ε4/ε4). Risco Alzheimer ~12-15× vs ε3/ε3, idade média de início ~68 anos.",
    },
    clinicalSignificance: "pathogenic",
    sensitive: true,
    references: [
      { label: "Corder EH, et al. Science 1993", pmid: "8346443" },
      { label: "Farrer LA, et al. JAMA 1997 (meta-análise)", pmid: "9343467" },
      { label: "Genin E, et al. Mol Psychiatry 2011", pmid: "21577212" },
      { label: "ClinVar: APOE", url: "https://www.ncbi.nlm.nih.gov/clinvar/?term=APOE" },
    ],
    populationNotes: "Frequência ε4: ~14% global, ~40% em nigerianos Yoruba (paradoxalmente sem aumento proporcional de Alzheimer — 'paradoxo de ε4'), ~10-15% em europeus, ~6% em leste-asiáticos.",
    actionable: "Se ε4/ε4: monitoramento cognitivo regular a partir de 60 anos; atividade aeróbica ≥150 min/sem reduz risco ~40%; sono adequado, controle de PA e colesterol, educação continuada, dieta MIND. NUNCA interprete este resultado sem apoio médico.",
    notes: "O risco é relativo e modificável. Apenas ~1/3 dos ε4/ε4 desenvolvem Alzheimer até 85 anos. Fatores protetores compensam substancialmente.",
    tags: ["alzheimer", "demência", "neurologia"],
  },
  {
    rsid: "rs7412",
    gene: "APOE",
    geneFullName: "APOE — Apolipoprotein E (variante ε2)",
    chrom: "19",
    position: 45412079,
    category: "health",
    title: "APOE ε2 — SNP complementar para haplótipo APOE",
    shortDesc: "Combinado com rs429358 define os haplótipos APOE. O alelo T aqui marca o braço ε2.",
    longDesc: "Necessário em conjunto com rs429358 para genotipar APOE completamente. A isoforma ε2 é protetora contra Alzheimer (reduz risco ~40%) mas aumenta risco de hiperlipoproteinemia tipo III (quilomícrons e VLDL elevados) em homozigotos. Aproximadamente 1/150 é ε2/ε2.",
    interpretations: {
      CC: "Não tem ε2 (genótipo ε3/ε3, ε3/ε4 ou ε4/ε4 dependendo de rs429358).",
      CT: "Heterozigoto — uma cópia ε2.",
      TT: "Homozigoto — ε2/ε2. Proteção Alzheimer mas risco de hiperlipoproteinemia tipo III (~10% penetrância).",
    },
    sensitive: true,
    references: [
      { label: "Mahley RW, et al. J Lipid Res 1999", pmid: "10428971" },
    ],
    tags: ["alzheimer", "lipídios"],
  },
  {
    rsid: "rs6025",
    gene: "F5",
    geneFullName: "F5 — Coagulation Factor V (Leiden, R506Q)",
    chrom: "1",
    position: 169519049,
    category: "health",
    title: "Fator V Leiden — trombose venosa profunda",
    shortDesc: "Mutação que torna o Fator V resistente à clivagem pela Proteína C ativada — estado pró-trombótico.",
    longDesc: "A mutação R506Q (Arg506→Gln) elimina um dos sítios de clivagem do Fator Va pela Proteína C ativada (APC), prolongando sua atividade procoagulante. É a causa hereditária mais comum de trombofilia em europeus (~5% heterozigotos). Eventos típicos: TVP de membros inferiores, TEP, trombose de veia cerebral ou mesentérica. Risco muito elevado combinado com estrogênio (anticoncepcional oral, TRH) ou imobilidade.",
    mechanism: "Em condições normais, APC cliva Fator Va em Arg506 e inativa-o. A mutação Leiden elimina esse sítio, resultando em atividade procoagulante prolongada (~10×). Pessoas sem Leiden também têm variabilidade nisto, mas Leiden é o efeito mais dramático conhecido.",
    interpretations: {
      CC: "Selvagem — sem variante Leiden.",
      CT: "Heterozigoto — risco de TVP ao longo da vida ~5-10× (de ~0,1%/ano para ~0,5-1%/ano). ACO aumenta risco ~35×.",
      TT: "Homozigoto — risco ~80×. Raro (~1 em 5000). Anticoagulação profilática pode ser indicada em situações de alto risco.",
    },
    clinicalSignificance: "pathogenic",
    sensitive: true,
    references: [
      { label: "Bertina RM, et al. Nature 1994", pmid: "8164741" },
      { label: "Ridker PM, et al. NEJM 1995", pmid: "7609915" },
      { label: "ACMG guideline: Factor V Leiden", pmid: "11391554" },
    ],
    populationNotes: "Frequência do T: ~5% em europeus, ~1-2% em Oriente Médio, raríssimo em africanos e leste-asiáticos.",
    actionable: "Se heterozigoto: evitar ACO combinado; em viagens >4h usar meias de compressão, hidratar, mobilizar-se. Se TEV prévio + Leiden: anticoagulação por ≥3 meses, avaliação especializada para extensão. Se homozigoto: anticoagulação prolongada após primeiro evento costuma ser indicada.",
    notes: "NUNCA interprete isoladamente. Procure hematologista se houver histórico pessoal ou familiar de trombose.",
    tags: ["trombose", "coagulação", "hematologia"],
  },
  {
    rsid: "rs1799963",
    gene: "F2",
    geneFullName: "F2 — Prothrombin (G20210A)",
    chrom: "11",
    position: 46761055,
    category: "health",
    title: "Protrombina G20210A — trombofilia",
    shortDesc: "Variante na região 3' UTR do gene da protrombina que aumenta níveis plasmáticos da protrombina.",
    longDesc: "A mutação G20210A na região não-traduzida 3' do gene da protrombina aumenta a estabilidade do mRNA, elevando protrombina plasmática ~30%. Causa a segunda trombofilia hereditária mais comum em europeus (após Fator V Leiden). Risco combinado (dupla heterozigose F5 Leiden + F2 G20210A) é sinérgico.",
    interpretations: {
      GG: "Selvagem.",
      AG: "Heterozigoto — risco de TVP ~2-3×. Risco sinérgico com ACO ou Leiden.",
      AA: "Homozigoto — raríssimo, risco significativamente maior; casos de trombose arterial também relatados.",
    },
    clinicalSignificance: "pathogenic",
    sensitive: true,
    references: [
      { label: "Poort SR, et al. Blood 1996", pmid: "8916933" },
    ],
    populationNotes: "Frequência do A: ~2% em europeus, raro em outras populações.",
    actionable: "Similar à abordagem de Leiden: se heterozigoto + histórico pessoal/familiar, avaliação hematológica; cautela com ACO e imobilidade prolongada.",
    tags: ["trombose", "coagulação"],
  },
  {
    rsid: "rs1800562",
    gene: "HFE",
    geneFullName: "HFE — Homeostatic Iron Regulator (C282Y)",
    chrom: "6",
    position: 26093141,
    category: "health",
    title: "Hemocromatose hereditária — C282Y",
    shortDesc: "Mutação C282Y homozigota é a causa genética mais comum de sobrecarga de ferro em europeus.",
    longDesc: "HFE regula a síntese de hepcidina, o hormônio que controla absorção intestinal de ferro. A mutação C282Y impede dimerização de HFE com β2-microglobulina e transporte à membrana, resultando em hepcidina baixa e absorção aumentada crônica de ferro. Penetrância clínica é INCOMPLETA (~30% dos homens e ~10% das mulheres homozigotos desenvolvem sintomas) — mulheres são parcialmente protegidas por perdas menstruais e gestação. Sintomas típicos: fadiga, artralgia (MCP 2ª-3ª), cirrose hepática, hiperpigmentação cutânea, DM, cardiomiopatia, hipogonadismo.",
    mechanism: "HFE forma complexo com TfR2 para sinalizar hepcidina no hepatócito. C282Y (Cys282Tyr) impede formação da ponte dissulfeto com β2m, a proteína não atinge a membrana → hepcidina cai → absorção intestinal sobe → ferro acumula em fígado, coração, pâncreas, pele.",
    interpretations: {
      GG: "Selvagem — sem C282Y.",
      AG: "Portador — geralmente assintomático isolado. Risco modesto se combinado com H63D (rs1799945).",
      AA: "Homozigoto — penetrância 10-30% para hemocromatose clínica. Ferritina e saturação de transferrina devem ser monitoradas.",
    },
    clinicalSignificance: "pathogenic",
    sensitive: true,
    references: [
      { label: "Feder JN, et al. Nat Genet 1996", pmid: "8696333" },
      { label: "Adams PC, et al. NEJM 2005", pmid: "15858186" },
      { label: "AASLD guideline 2011", pmid: "21452290" },
    ],
    populationNotes: "Frequência de C282Y: ~6-10% em europeus do norte, praticamente ausente em africanos e asiáticos.",
    actionable: "Se homozigoto: medir ferritina e saturação de transferrina. Se elevadas → flebotomia terapêutica (simples, eficaz). Evitar suplementos de ferro e vitamina C em altas doses. Rastreio familiar.",
    tags: ["ferro", "fígado", "hereditário"],
  },
  {
    rsid: "rs1799945",
    gene: "HFE",
    geneFullName: "HFE — Homeostatic Iron Regulator (H63D)",
    chrom: "6",
    position: 26091179,
    category: "health",
    title: "HFE H63D — sobrecarga de ferro leve",
    shortDesc: "Variante modesta isoladamente; clinicamente relevante combinada com C282Y (heterozigose composta).",
    longDesc: "H63D é uma variante mais leve que C282Y. Homozigose H63D isolada raramente causa doença. Heterozigose composta C282Y/H63D tem penetrância intermediária — ~1-2% desenvolvem sobrecarga clínica.",
    interpretations: {
      CC: "Selvagem.",
      CG: "Heterozigoto — risco modesto, clinicamente insignificante isolado.",
      GG: "Homozigoto — risco baixo isolado; maior se combinado com C282Y.",
    },
    clinicalSignificance: "vus",
    references: [
      { label: "Adams PC, et al. Hepatology 2006", pmid: "16779801" },
    ],
    tags: ["ferro"],
  },
  {
    rsid: "rs7903146",
    gene: "TCF7L2",
    geneFullName: "TCF7L2 — Transcription Factor 7 Like 2",
    chrom: "10",
    position: 114758349,
    category: "health",
    title: "TCF7L2 — diabetes tipo 2 (SNP de maior efeito comum)",
    shortDesc: "Variante comum de maior efeito conhecido para DM2 em população geral.",
    longDesc: "TCF7L2 é um fator de transcrição da via Wnt envolvido no desenvolvimento de células β pancreáticas. A variante T em rs7903146 no íntron 4 é a variante comum de maior efeito para DM2 descoberta até hoje. Efeito via secreção de insulina deficiente (não resistência). Também afeta risco de diabetes gestacional.",
    mechanism: "O alelo T aumenta expressão de TCF7L2 em ilhotas, desregulando secreção de insulina estimulada por glicose. Também reduz GLP-1 pós-prandial.",
    interpretations: {
      CC: "Sem alelo de risco T — risco basal populacional.",
      CT: "Uma cópia T — OR ~1,4 (risco relativo ~40% maior que o basal).",
      TT: "Duas cópias T — OR ~1,9 (~2× o risco basal).",
    },
    references: [
      { label: "Grant SF, et al. Nat Genet 2006", pmid: "16415884" },
      { label: "Florez JC, et al. NEJM 2006", pmid: "16855265" },
    ],
    populationNotes: "Frequência do T: ~30% em europeus, ~35% em africanos, ~5% em leste-asiáticos (outros SNPs contribuem mais lá).",
    actionable: "Dieta com baixa carga glicêmica, exercício regular (especialmente força + aeróbico combinados), controle de peso — reduzem risco substancialmente independente do genótipo. Metformina em pré-diabetes neutraliza grande parte do excesso de risco conferido por TCF7L2.",
    notes: "O efeito é modificável por estilo de vida. Não é sentença.",
    tags: ["diabetes", "metabólico"],
  },
  {
    rsid: "rs1061170",
    gene: "CFH",
    geneFullName: "CFH — Complement Factor H (Y402H)",
    chrom: "1",
    position: 196659237,
    category: "health",
    title: "CFH Y402H — degeneração macular relacionada à idade",
    shortDesc: "Variante no principal regulador do complemento, maior contribuinte comum conhecido para DMRI.",
    longDesc: "Y402H altera a capacidade de CFH de se ligar a glicosaminoglicanos e C-reactive protein na retina, favorecendo ativação crônica do complemento e dano dos fotorreceptores. Explica ~20% do risco atribuível de DMRI em população geral.",
    interpretations: {
      TT: "Baixo risco.",
      CT: "Risco ~2-4× (heterozigoto).",
      CC: "Risco ~5-7× (homozigoto).",
    },
    references: [
      { label: "Klein RJ, et al. Science 2005", pmid: "15761120" },
      { label: "Hageman GS, et al. PNAS 2005", pmid: "15870199" },
    ],
    actionable: "Não fumar (tabagismo multiplica o risco), AREDS2 (luteína, zeaxantina, zinco, cobre) se já houver drusas; avaliação oftalmológica anual após 50 anos.",
    tags: ["visão", "ocular"],
  },
  {
    rsid: "rs1801133",
    gene: "MTHFR",
    geneFullName: "MTHFR — Methylenetetrahydrofolate Reductase (C677T)",
    chrom: "1",
    position: 11856378,
    category: "health",
    title: "MTHFR C677T — metabolismo de folato",
    shortDesc: "Variante termolábil que reduz atividade enzimática, afetando metabolismo de folato e homocisteína.",
    longDesc: "MTHFR converte 5,10-metilenoTHF em 5-metilTHF, doador de metila para conversão de homocisteína em metionina. A variante C677T (Ala222Val) gera uma enzima termolábil com atividade reduzida. CUIDADO: o 'MTHFR' ganhou fama exagerada em mídia de saúde — a significância clínica real é modesta e suplementação rotineira de metilfolato NÃO é recomendada baseada apenas no genótipo.",
    interpretations: {
      GG: "Atividade enzimática normal (~100%).",
      AG: "Heterozigoto — atividade ~65%.",
      AA: "Homozigoto — atividade ~30%. Homocisteína pode estar discretamente elevada com folato dietético insuficiente.",
    },
    clinicalSignificance: "vus",
    references: [
      { label: "Frosst P, et al. Nat Genet 1995", pmid: "7647779" },
      { label: "ACMG practice guideline 2013", pmid: "23288205" },
    ],
    actionable: "Não suplementar metilfolato rotineiramente sem homocisteína alta documentada. Folato dietético adequado (folhas verdes, leguminosas) é suficiente para maioria dos TT.",
    notes: "A ACMG recomenda que MTHFR NÃO seja testado em contexto clínico rotineiro — o valor preditivo é baixo.",
    tags: ["metilação", "folato"],
  },

  // ================ PHARMACO ================
  {
    rsid: "rs4244285",
    gene: "CYP2C19",
    geneFullName: "CYP2C19 *2 — Cytochrome P450 2C19 (perda de função)",
    chrom: "10",
    position: 96541616,
    category: "pharmaco",
    title: "CYP2C19 *2 — clopidogrel, PPIs, voriconazol",
    shortDesc: "Alelo mais comum de perda de função do CYP2C19. Portadores são metabolizadores intermediários ou lentos.",
    longDesc: "CYP2C19 é responsável pela bioativação do clopidogrel (Plavix) em seu metabólito ativo. Em metabolizadores lentos, clopidogrel pode ser INEFICAZ para prevenção de eventos cardiovasculares — ticagrelor ou prasugrel são alternativas indicadas. Também afeta: omeprazol (melhor eficácia anti-H. pylori em lentos), voriconazol (risco de toxicidade em lentos), alguns SSRIs (citalopram, escitalopram).",
    mechanism: "A variante 681G>A gera splice defeituoso do éxon 5, produzindo proteína truncada sem atividade.",
    interpretations: {
      GG: "Provável *1/*1 — metabolizador normal (sem *17 em cis).",
      AG: "Provável *1/*2 — metabolizador intermediário.",
      AA: "*2/*2 — metabolizador lento. Clopidogrel pode ter eficácia reduzida.",
    },
    references: [
      { label: "CPIC clopidogrel guideline 2013", pmid: "23698643" },
      { label: "Scott SA, et al. CPT 2013", pmid: "23698643" },
      { label: "PharmGKB: CYP2C19", url: "https://www.pharmgkb.org/gene/PA124" },
    ],
    populationNotes: "Frequência *2: ~15% em europeus, ~30% em leste-asiáticos, ~17% em africanos.",
    actionable: "Se inicia clopidogrel após SCA ou stent: considerar genotipagem. Lento → trocar por ticagrelor ou prasugrel. IMPORTANTE: sempre em conjunto com cardiologista.",
    tags: ["CPIC", "anticoagulante", "farmácia"],
  },
  {
    rsid: "rs12248560",
    gene: "CYP2C19",
    geneFullName: "CYP2C19 *17 — ganho de função",
    chrom: "10",
    position: 96521657,
    category: "pharmaco",
    title: "CYP2C19 *17 — metabolizador ultrarrápido",
    shortDesc: "Variante promotora que aumenta expressão. Portadores metabolizam CYP2C19-substratos rápido demais.",
    longDesc: "O alelo *17 (-806C>T) aumenta transcrição do CYP2C19 e produz fenótipo de metabolizador rápido/ultrarrápido. Para PPIs pode gerar falha terapêutica (dose subótima para H. pylori); para clopidogrel paradoxalmente pode aumentar risco de sangramento (mais metabólito ativo); para escitalopram maior necessidade de dose.",
    interpretations: {
      CC: "Sem *17.",
      CT: "Heterozigoto — metabolizador rápido.",
      TT: "Homozigoto — metabolizador ultrarrápido. PPIs podem precisar dose aumentada; cuidado com sangramento em clopidogrel.",
    },
    references: [
      { label: "Sim SC, et al. CPT 2006", pmid: "16988502" },
    ],
    tags: ["CPIC", "farmácia"],
  },
  {
    rsid: "rs1799853",
    gene: "CYP2C9",
    geneFullName: "CYP2C9 *2 (R144C)",
    chrom: "10",
    position: 96702047,
    category: "pharmaco",
    title: "CYP2C9 *2 — varfarina, AINEs, fenitoína",
    shortDesc: "Reduz atividade metabólica moderadamente — dose menor de varfarina tipicamente necessária.",
    longDesc: "CYP2C9 metaboliza S-varfarina (mais potente que R), fenitoína, losartana, AINEs (celecoxibe, ibuprofeno), sulfonilureias. *2 reduz atividade ~50%. Em combinação com *3 e VKORC1 explica ~40% da variabilidade de dose de varfarina em europeus.",
    interpretations: {
      CC: "Sem *2 — metabolismo normal.",
      CT: "Heterozigoto — sensibilidade aumentada a varfarina.",
      TT: "Homozigoto — metabolizador lento.",
    },
    references: [
      { label: "CPIC warfarin guideline 2017", pmid: "28198005" },
    ],
    tags: ["CPIC", "varfarina"],
  },
  {
    rsid: "rs1057910",
    gene: "CYP2C9",
    geneFullName: "CYP2C9 *3 (I359L)",
    chrom: "10",
    position: 96741053,
    category: "pharmaco",
    title: "CYP2C9 *3 — varfarina (efeito maior que *2)",
    shortDesc: "Alelo de perda de função mais forte; impacta significativamente a dose de varfarina.",
    longDesc: "*3 reduz atividade ~80-90% e tem efeito maior em dose de varfarina. Homozigotos *3/*3 podem precisar de 1/5 da dose padrão.",
    interpretations: {
      AA: "Sem *3.",
      AC: "Heterozigoto.",
      CC: "Homozigoto — metabolizador lento. Varfarina altamente sensível.",
    },
    references: [
      { label: "CPIC warfarin guideline 2017", pmid: "28198005" },
    ],
    tags: ["CPIC", "varfarina"],
  },
  {
    rsid: "rs9923231",
    gene: "VKORC1",
    geneFullName: "VKORC1 — Vitamin K Epoxide Reductase Complex Subunit 1",
    chrom: "16",
    position: 31107689,
    category: "pharmaco",
    title: "VKORC1 — sensibilidade à varfarina",
    shortDesc: "Alelo A reduz expressão do alvo da varfarina — doses significativamente menores.",
    longDesc: "VKORC1 é o alvo molecular da varfarina. O SNP -1639G>A (rs9923231) na região promotora reduz expressão. Sozinho explica ~30% da variabilidade de dose.",
    interpretations: {
      GG: "Dose padrão.",
      AG: "Sensibilidade intermediária — ~30% redução de dose.",
      AA: "Alta sensibilidade — ~50% redução de dose.",
    },
    references: [
      { label: "Rieder MJ, et al. NEJM 2005", pmid: "15930419" },
      { label: "CPIC warfarin guideline 2017", pmid: "28198005" },
    ],
    populationNotes: "Frequência do A: ~40% em europeus, ~90% em leste-asiáticos (explica dose menor típica em asiáticos).",
    tags: ["CPIC", "varfarina"],
  },
  {
    rsid: "rs4149056",
    gene: "SLCO1B1",
    geneFullName: "SLCO1B1 — Solute Carrier Organic Anion Transporter 1B1 (T521C, V174A)",
    chrom: "12",
    position: 21331549,
    category: "pharmaco",
    title: "SLCO1B1 — miopatia com sinvastatina",
    shortDesc: "Variante reduz transporte hepático de sinvastatina; aumenta exposição muscular e risco de miopatia.",
    longDesc: "SLCO1B1 (OATP1B1) é o transportador que retira sinvastatina (e em menor grau, pitavastatina e atorvastatina) da circulação para o fígado. T521C reduz essa captação → exposição sistêmica aumentada → mais miopatia (mialgia, rabdomiólise). Dose 80 mg sinvastatina em CC tem risco de miopatia ~17× vs TT. Rosuvastatina e pravastatina são alternativas mais seguras em CC.",
    interpretations: {
      TT: "Função normal — sinvastatina em dose padrão tolerada.",
      CT: "Função intermediária — evitar sinvastatina 80 mg; 40 mg aceitável.",
      CC: "Função baixa — evitar sinvastatina >20 mg. Rosuvastatina/pravastatina preferíveis.",
    },
    references: [
      { label: "SEARCH collaborative, NEJM 2008", pmid: "18650507" },
      { label: "CPIC statin guideline 2022", pmid: "35152406" },
    ],
    populationNotes: "Frequência do C: ~15% em europeus, ~10% em leste-asiáticos, ~2% em africanos.",
    tags: ["CPIC", "estatina", "cardiologia"],
  },
  {
    rsid: "rs3892097",
    gene: "CYP2D6",
    geneFullName: "CYP2D6 *4 (splicing)",
    chrom: "22",
    position: 42524947,
    category: "pharmaco",
    title: "CYP2D6 *4 — codeína, tramadol, tamoxifeno, SSRIs",
    shortDesc: "Alelo de perda de função mais comum em europeus. Microarray NÃO detecta duplicações (UM).",
    longDesc: "CYP2D6 metaboliza ~25% das drogas prescritas. *4 é o alelo de perda de função mais comum em europeus (~20% de frequência). Metabolizadores lentos têm: codeína sem analgesia (prodroga, não bioativada), tamoxifeno com eficácia reduzida em câncer de mama, risco aumentado de efeitos colaterais de antidepressivos (tricíclicos, SSRIs). ATENÇÃO: microarrays NÃO detectam duplicações e deleções, portanto NÃO identificam metabolizadores ultrarrápidos (*1xN) — que são perigosos para codeína em crianças (morte por intoxicação por morfina).",
    interpretations: {
      CC: "Sem *4.",
      CT: "Heterozigoto — metabolizador intermediário.",
      TT: "*4/*4 homozigoto — metabolizador lento. Codeína sem efeito analgésico esperado. Usar morfina ou outro opioide.",
    },
    references: [
      { label: "CPIC codeine guideline 2014", pmid: "24458010" },
      { label: "PharmGKB: CYP2D6", url: "https://www.pharmgkb.org/gene/PA128" },
    ],
    populationNotes: "Frequência *4: ~20% em europeus, raro em asiáticos (nesses, *10 é o mais comum).",
    notes: "Para fenotipagem completa é necessário sequenciamento com detecção de variação de número de cópias (CNV).",
    tags: ["CPIC", "dor", "psiquiatria"],
  },

  // ================ NUTRI ================
  {
    rsid: "rs4988235",
    gene: "MCM6/LCT",
    geneFullName: "MCM6 — Minichromosome Maintenance Complex Component 6 (regulador de LCT)",
    chrom: "2",
    position: 136608646,
    category: "nutri",
    title: "Persistência de lactase (variante europeia)",
    shortDesc: "Variante regulatória a 14 kb do gene LCT — permite digerir lactose na vida adulta.",
    longDesc: "Em mamíferos a lactase normalmente é silenciada após o desmame. Esta variante em um intensificador a 14 kb upstream do LCT mantém expressão da lactase no enterócito adulto — um caso clássico de EVOLUÇÃO CONVERGENTE em humanos. Três variantes diferentes (rs4988235 em europeus, rs41380347 em africanos Massai, rs145946881 em árabes) resolvem o mesmo problema via mecanismos similares — todas no mesmo enhancer.",
    mechanism: "A variante T cria sítio de ligação para Oct-1 (POU2F1), mantendo cromatina aberta no enhancer LCT14 em enterócitos adultos → expressão persistente da lactase → digestão de lactose dietética.",
    interpretations: {
      AA: "Persistência total — tolera lactose na vida adulta (variante europeia).",
      AG: "Persistência parcial — tolera lactose na maioria das situações.",
      GG: "Não persistente — má digestão de lactose provável após a primeira infância.",
    },
    references: [
      { label: "Enattah NS, et al. Nat Genet 2002", pmid: "11788828" },
      { label: "Tishkoff SA, et al. Nat Genet 2007 (variantes africanas)", pmid: "17159977" },
    ],
    populationNotes: "Frequência T: ~80% escandinavos, ~60% europeus do sul, <10% leste-asiáticos, variável em africanos (outras variantes contribuem).",
    actionable: "Se GG com sintomas (gases, diarréia, distensão após laticínios): restrição de lactose, uso de lactase oral, ou produtos sem lactose. Iogurte e queijos duros são geralmente tolerados mesmo em não-persistentes.",
    tags: ["lactose", "digestão"],
  },
  {
    rsid: "rs762551",
    gene: "CYP1A2",
    geneFullName: "CYP1A2 — Cytochrome P450 1A2",
    chrom: "15",
    position: 75041917,
    category: "nutri",
    title: "CYP1A2 — metabolismo da cafeína",
    shortDesc: "Define metabolizadores rápidos vs lentos de cafeína.",
    longDesc: "CYP1A2 metaboliza ~95% da cafeína. A variante *1F (-163C>A) afeta indutibilidade enzimática. Rápidos eliminam cafeína com t½ ~4h; lentos t½ >6h. Em metabolizadores lentos, consumo de 2-3+ xícaras/dia de café está associado a maior risco de infarto e hipertensão — efeito que NÃO ocorre em metabolizadores rápidos.",
    interpretations: {
      AA: "Metabolizador rápido — cafeína eliminada rapidamente, sem aumento de risco CV por consumo moderado.",
      AC: "Intermediário.",
      CC: "Metabolizador lento — consumo >2 xícaras/dia associado a maior risco CV em estudos.",
    },
    references: [
      { label: "Cornelis MC, et al. JAMA 2006", pmid: "16522833" },
      { label: "Palatini P, et al. J Hypertens 2009", pmid: "19155785" },
    ],
    actionable: "Se lento: reduzir cafeína vespertina (sono); limitar consumo se houver hipertensão ou histórico CV.",
    tags: ["cafeína", "metabolismo"],
  },
  {
    rsid: "rs9939609",
    gene: "FTO",
    geneFullName: "FTO — Fat Mass and Obesity Associated",
    chrom: "16",
    position: 53820527,
    category: "nutri",
    title: "FTO — IMC, apetite e saciedade",
    shortDesc: "Variante comum mais fortemente associada a IMC em população geral.",
    longDesc: "A região FTO no cromossomo 16 contém a variante comum de maior efeito para IMC (~1 kg/alelo em adultos europeus). O mecanismo envolve enhancer de longa distância regulando IRX3 e IRX5 em precursores adipocíticos. Afeta também apetite, saciedade pós-prandial e escolha alimentar. Efeito TOTALMENTE atenuado por atividade física regular em estudos.",
    mechanism: "O SNP de risco afeta enhancer regulador de IRX3/IRX5 em adipócitos, alterando balanço térmico (menor termogênese, mais armazenamento). Também modula hipotálamo via MC4R.",
    interpretations: {
      TT: "Sem alelo de risco — IMC médio populacional.",
      AT: "Uma cópia A — ~+1,2 kg em adultos.",
      AA: "Duas cópias A — ~+3 kg em adultos, maior relato de fome e menor saciedade.",
    },
    references: [
      { label: "Frayling TM, et al. Science 2007", pmid: "17434869" },
      { label: "Kilpeläinen TO, et al. PLoS Med 2011", pmid: "22069379" },
    ],
    actionable: "Atividade física regular (~150 min/sem) elimina o aumento de risco conferido. Atenção a fome 'recompensada' vs fome fisiológica.",
    tags: ["peso", "apetite"],
  },
  {
    rsid: "rs602662",
    gene: "FUT2",
    geneFullName: "FUT2 — Fucosyltransferase 2 (secretor vs não-secretor)",
    chrom: "19",
    position: 49206985,
    category: "nutri",
    title: "FUT2 — secretor, B12 e norovírus",
    shortDesc: "Não-secretores têm menor B12 sérica, microbiota distinta e resistência genética ao norovírus.",
    longDesc: "FUT2 adiciona fucose a antígenos ABH em muco e secreções. Não-secretores (homozigotos para perda de função) não expressam esses antígenos, o que: (1) reduz absorção de B12 (antígenos atuam como receptores em Helicobacter pylori e Bifidobacterium); (2) altera microbiota intestinal; (3) CONFERE RESISTÊNCIA quase total ao norovírus GII.4 (o principal causador de gastroenterite viral).",
    interpretations: {
      AA: "Secretor (homozigoto).",
      AG: "Heterozigoto secretor.",
      GG: "Não-secretor — B12 sérica tende menor; microbiota distinta; resistência ao norovírus mais comum.",
    },
    references: [
      { label: "Tanwar VS, et al. PLoS Genet 2012", pmid: "23166518" },
      { label: "Lindesmith L, et al. Nat Med 2003", pmid: "12692542" },
    ],
    actionable: "Não-secretores podem se beneficiar de monitoramento de B12 em dietas vegetarianas/veganas.",
    tags: ["B12", "microbiota"],
  },
  {
    rsid: "rs174537",
    gene: "FADS1",
    geneFullName: "FADS1 — Fatty Acid Desaturase 1",
    chrom: "11",
    position: 61552680,
    category: "nutri",
    title: "FADS1 — conversão de ômega-3 (ALA → EPA/DHA)",
    shortDesc: "Variante reguladora de FADS1/2 que determina eficiência de conversão de ALA em EPA/DHA.",
    longDesc: "ALA (ácido α-linolênico, de sementes vegetais) precisa ser convertido em EPA e DHA para ação biológica. FADS1/2 são as dessaturases responsáveis. A variante TT resulta em conversão significativamente reduzida (~10% eficiência vs GG) — nesses indivíduos, obter ômega-3 exclusivamente de fontes vegetais (chia, linhaça) pode ser insuficiente; fontes marinhas diretas (peixes gordos, óleo de peixe, microalga) são recomendadas.",
    interpretations: {
      GG: "Conversão eficiente — fontes vegetais de ALA podem suprir parcialmente.",
      GT: "Intermediário.",
      TT: "Conversão reduzida — priorizar EPA/DHA direto (peixes gordos, algas).",
    },
    references: [
      { label: "Schaeffer L, et al. Hum Mol Genet 2006", pmid: "16556607" },
    ],
    tags: ["ômega-3", "lipídios"],
  },
  {
    rsid: "rs2282679",
    gene: "GC",
    geneFullName: "GC — Vitamin D Binding Protein",
    chrom: "4",
    position: 72618334,
    category: "nutri",
    title: "GC — transporte de vitamina D",
    shortDesc: "Afeta níveis circulantes de 25(OH)D.",
    longDesc: "GC (DBP) é a principal proteína carreadora de vitamina D no sangue. A variante afeta afinidade e níveis de 25(OH)D, biomarcador padrão de status.",
    interpretations: {
      AA: "Níveis de vit. D mais altos em média.",
      AC: "Intermediário.",
      CC: "Níveis mais baixos — suplementação pode ser mais frequentemente indicada.",
    },
    references: [
      { label: "Wang TJ, et al. Lancet 2010", pmid: "20541252" },
    ],
    actionable: "Dosar 25(OH)D ao invés de guiar conduta apenas pelo genótipo.",
    tags: ["vitamina D"],
  },

  // ================ SPORT ================
  {
    rsid: "rs1815739",
    gene: "ACTN3",
    geneFullName: "ACTN3 — α-Actinin-3 (R577X)",
    chrom: "11",
    position: 66560624,
    category: "sport",
    title: "ACTN3 R577X — fast-twitch vs endurance",
    shortDesc: "A α-actinina-3 é expressa apenas em fibras musculares rápidas. A variante X577 (stop codon) elimina a proteína.",
    longDesc: "ACTN3 codifica α-actinina-3, componente estrutural exclusivo de fibras rápidas tipo 2 (fast-twitch). A variante R577X introduz stop codon prematuro — homozigotos X/X (TT em rs1815739) não têm α-actinina-3 em absoluto, compensada por α-actinina-2. Estudos em atletas de elite mostram: R/R super-representado em velocistas e halterofilistas; X/X super-representado em atletas de endurance. Efeito real em indivíduos amadores é pequeno — não determina potencial atlético isoladamente.",
    mechanism: "Sem α-actinina-3, fibras rápidas têm metabolismo mais oxidativo (tipo 2A ao invés de 2X), favorecendo endurance mas não potência explosiva.",
    interpretations: {
      CC: "R/R — α-actinina-3 funcional. Sobre-representado em sprinters e halterofilistas de elite.",
      CT: "R/X — fenótipo misto (maioria da população).",
      TT: "X/X — sem α-actinina-3. Sobre-representado em atletas de endurance; possivelmente maior tendinopatia, pior recuperação de dano muscular excêntrico.",
    },
    references: [
      { label: "Yang N, et al. AJHG 2003", pmid: "12930503" },
      { label: "MacArthur DG, et al. Nat Genet 2007", pmid: "17529977" },
    ],
    populationNotes: "~18% europeus são X/X. Raríssimo em africanos sub-saarianos (variante praticamente ausente — pressão seletiva hipotética).",
    actionable: "Interessante para curiosidade atlética. NÃO é determinante — treino especializado supera genética em amadores.",
    tags: ["performance", "músculo"],
  },
  {
    rsid: "rs4680",
    gene: "COMT",
    geneFullName: "COMT — Catechol-O-Methyltransferase (Val158Met)",
    chrom: "22",
    position: 19951271,
    category: "sport",
    title: "COMT Val158Met — dopamina, foco, dor",
    shortDesc: "Val = warrior (metabolização rápida de dopamina); Met = worrier (lenta, dopamina basal maior no córtex pré-frontal).",
    longDesc: "COMT degrada catecolaminas (dopamina, norepi, epi). A variante G/A (Val158→Met158) tem uma cinética mais lenta (atividade ~25-40% menor em Met/Met). Resultado: Met/Met tem mais dopamina sináptica basal no PFC — melhor desempenho em tarefas de memória de trabalho em condições neutras, pior sob estresse agudo (sobrecarrega o sistema). Val/Val tolera estresse melhor ('warrior') mas tem desempenho cognitivo médio menor em tarefas sustentadas. Também influencia limiar de dor.",
    mechanism: "Val → enzima termoestável com meia-vida 2-3× maior que Met → degradação rápida de dopamina → menos dopamina basal cortical.",
    interpretations: {
      GG: "Val/Val — warrior. Melhor performance sob estresse; menor dopamina tônica; maior limiar de dor.",
      AG: "Val/Met — heterozigoto, fenótipo intermediário.",
      AA: "Met/Met — worrier. Melhor foco em tarefas de detalhe neutras; mais vulnerável a queda de performance sob estresse; menor limiar de dor.",
    },
    references: [
      { label: "Egan MF, et al. PNAS 2001", pmid: "11381111" },
      { label: "Mier D, et al. Mol Psychiatry 2010 (meta)", pmid: "19884892" },
    ],
    notes: "O efeito é modesto (~5-10% de variância em tarefas cognitivas). NÃO determina personalidade.",
    tags: ["neurociência", "dopamina"],
  },
  {
    rsid: "rs1800795",
    gene: "IL6",
    geneFullName: "IL6 — Interleukin 6 (promotor -174G>C)",
    chrom: "7",
    position: 22766645,
    category: "sport",
    title: "IL-6 -174 — inflamação e recuperação",
    shortDesc: "Variante no promotor afeta expressão basal de IL-6.",
    longDesc: "IL-6 é citocina-chave em inflamação e reparo muscular após exercício. O SNP -174 no promotor afeta expressão basal e induzida. G → expressão maior, estado pró-inflamatório tônico. C → expressão menor, resposta aguda preservada mas inflamação basal menor.",
    interpretations: {
      GG: "Expressão IL-6 mais alta — inflamação basal maior. Possivelmente maior sarcopenia na velhice.",
      CG: "Intermediário.",
      CC: "Expressão mais baixa — possivelmente melhor recuperação após exercício.",
    },
    references: [
      { label: "Fishman D, et al. J Clin Invest 1998", pmid: "9733513" },
    ],
    tags: ["inflamação", "recuperação"],
  },
  {
    rsid: "rs12722",
    gene: "COL5A1",
    geneFullName: "COL5A1 — Collagen Type V Alpha 1 Chain",
    chrom: "9",
    position: 137721626,
    category: "sport",
    title: "COL5A1 — flexibilidade e tendinopatia",
    shortDesc: "Variante em gene de colágeno tipo V associada a risco de lesões tendíneas e amplitude articular.",
    longDesc: "Colágeno tipo V compõe e regula fibrilas de colágeno tipo I. A variante no 3' UTR de COL5A1 afeta estabilidade de mRNA e quantidade de proteína. TT está associado a menor flexibilidade ativa e maior risco de tendinite de Aquiles em corredores; CC, maior flexibilidade mas possivelmente maior risco de lesão ligamentar.",
    interpretations: {
      TT: "Maior risco de tendinopatia relatado em atletas de endurance.",
      CT: "Intermediário.",
      CC: "Menor risco de tendinopatia; flexibilidade tende a ser maior.",
    },
    references: [
      { label: "September AV, et al. AJSM 2009", pmid: "19264966" },
      { label: "Collins M, et al. J Sci Med Sport 2011", pmid: "21543262" },
    ],
    tags: ["tendão", "flexibilidade"],
  },
];

export function groupByCategory(snps: CanonicalSnp[]) {
  const g: Record<string, typeof snps> = {};
  for (const s of snps) {
    if (!g[s.category]) g[s.category] = [];
    g[s.category].push(s);
  }
  return g;
}

export const CATEGORY_LABELS: Record<string, string> = {
  trait: "Traços e aparência",
  health: "Saúde e risco clínico",
  pharmaco: "Farmacogenômica (CPIC)",
  nutri: "Nutrigenômica",
  sport: "Esporte, performance e neurobiologia",
};

export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  trait: "Características físicas e sensoriais visíveis — olhos, pele, paladar, olfato, cera de ouvido. Sem implicações clínicas diretas.",
  health: "Variantes com evidência robusta de associação a risco de doença ou fenótipo clínico. Interpretação requer contexto médico.",
  pharmaco: "Variantes com diretrizes CPIC (Clinical Pharmacogenetics Implementation Consortium) para ajuste de medicação.",
  nutri: "Interações gene-dieta validadas. Efeitos geralmente modestos e modulados por estilo de vida.",
  sport: "Variantes em fisiologia do exercício e neurociência comportamental. Interesse exploratório, não determinante.",
};

export const CATEGORY_COLORS: Record<string, string> = {
  trait: "#a78bfa",
  health: "#f87171",
  pharmaco: "#34d399",
  nutri: "#fbbf24",
  sport: "#60a5fa",
};

export function findCanonicalByRsid(rsid: string) {
  return CANONICAL_SNPS.find((s) => s.rsid === rsid);
}

export function categoryColor(cat?: string): string {
  return CATEGORY_COLORS[cat ?? ""] ?? "#22d3ee";
}
