import type { ChromosomeInfo } from "./types";

export const CHROM_INFO: Record<string, ChromosomeInfo> = {
  "1": {
    chrom: "1",
    commonName: "Cromossomo 1 — o maior",
    majorGenes: ["MTHFR", "CFH", "F5 (Leiden)", "AGT", "NOTCH2", "LMNA"],
    knownFor: "O maior cromossomo humano (~8% do genoma). Contém mais genes que qualquer outro. MTHFR (metilação), CFH (DMRI), F5 (Fator V Leiden) estão aqui.",
    notableConditions: ["Fator V Leiden", "DMRI (CFH)", "Diabetes MODY3 (HNF4A)"],
    pArm: "Braço curto — genes do desenvolvimento precoce",
    qArm: "Braço longo — MTHFR, F5, CFH",
  },
  "2": {
    chrom: "2",
    commonName: "Cromossomo 2 — fusão ancestral",
    majorGenes: ["LCT/MCM6", "ALK", "MYCN", "BCL11A", "TTN"],
    knownFor: "Resultado da fusão evolutiva de dois cromossomos ancestrais (primatas têm 2a e 2b separados). Contém TTN (maior gene do genoma) e o regulador da lactase (MCM6/LCT).",
    notableConditions: ["Persistência de lactase", "Anemia falciforme modifier (BCL11A)"],
  },
  "3": {
    chrom: "3",
    commonName: "Cromossomo 3",
    majorGenes: ["FOXP2", "VHL", "MLH1", "RAF1"],
    knownFor: "Abriga FOXP2 ('gene da fala'), VHL (doença de von Hippel-Lindau) e MLH1 (Lynch).",
    notableConditions: ["Síndrome de Lynch (MLH1)", "VHL"],
  },
  "4": {
    chrom: "4",
    commonName: "Cromossomo 4",
    majorGenes: ["HTT", "GC (DBP)", "ADH1B", "PKD2"],
    knownFor: "Contém HTT (doença de Huntington) e a proteína ligadora de vitamina D (GC). ADH1B (metabolismo de álcool) também mora aqui.",
    notableConditions: ["Doença de Huntington", "PKD autossômica dominante"],
  },
  "5": {
    chrom: "5",
    commonName: "Cromossomo 5",
    majorGenes: ["APC", "TERT", "NIPBL", "SLC22A5"],
    knownFor: "APC (polipose adenomatosa familiar, câncer colorretal) e TERT (telomerase).",
    notableConditions: ["Síndrome de Cri-du-chat (deleção 5p)", "PAF (APC)"],
  },
  "6": {
    chrom: "6",
    commonName: "Cromossomo 6 — MHC/HLA",
    majorGenes: ["HLA-A/B/C/DRB1/DQB1", "HFE", "TNF", "MUT"],
    knownFor: "Abriga o complexo MHC/HLA — a região mais polimórfica do genoma humano, crítica em imunidade e transplantes. HFE (hemocromatose) também está aqui.",
    notableConditions: ["Hemocromatose hereditária", "Doença celíaca (HLA-DQ2/DQ8)", "Ankylosing spondylitis (HLA-B27)"],
  },
  "7": {
    chrom: "7",
    commonName: "Cromossomo 7",
    majorGenes: ["CFTR", "TAS2R38", "BRAF", "IL6"],
    knownFor: "CFTR (fibrose cística), TAS2R38 (paladar amargo), IL6 (inflamação).",
    notableConditions: ["Fibrose cística", "Williams-Beuren (deleção 7q11)"],
  },
  "8": {
    chrom: "8",
    commonName: "Cromossomo 8",
    majorGenes: ["MYC", "FGFR1", "WRN"],
    knownFor: "MYC (proto-oncogene central em câncer). WRN (síndrome de Werner, envelhecimento precoce).",
    notableConditions: ["Síndrome de Werner"],
  },
  "9": {
    chrom: "9",
    commonName: "Cromossomo 9 — ABO",
    majorGenes: ["ABO", "COL5A1", "CDKN2A", "JAK2"],
    knownFor: "Determina o tipo sanguíneo ABO. CDKN2A (melanoma, câncer pancreático). JAK2 (policitemia vera).",
    notableConditions: ["Grupo sanguíneo ABO", "Leucemia BCR-ABL (t 9;22)"],
  },
  "10": {
    chrom: "10",
    commonName: "Cromossomo 10",
    majorGenes: ["TCF7L2", "CYP2C19", "CYP2C9", "PTEN", "RET"],
    knownFor: "Cluster CYP2C (CYP2C9, CYP2C19 — centrais em farmacogenômica) e TCF7L2 (DM2).",
    notableConditions: ["DM2 (TCF7L2)", "Síndrome de Cowden (PTEN)", "MEN2 (RET)"],
  },
  "11": {
    chrom: "11",
    commonName: "Cromossomo 11 — hemoglobinas",
    majorGenes: ["HBB", "F2 (protrombina)", "TH", "ACTN3", "FADS1/2", "OR6A2"],
    knownFor: "Cluster da β-globina (anemia falciforme, β-talassemia). F2 (trombofilia). ACTN3 (performance esportiva). Cluster de receptores olfativos.",
    notableConditions: ["Anemia falciforme", "β-talassemia", "Trombofilia (F2)"],
  },
  "12": {
    chrom: "12",
    commonName: "Cromossomo 12",
    majorGenes: ["SLCO1B1", "VWF", "KRAS", "HNF1A"],
    knownFor: "SLCO1B1 (miopatia com estatina). VWF (doença de von Willebrand). KRAS (oncogene).",
    notableConditions: ["Von Willebrand", "MODY3 (HNF1A)"],
  },
  "13": {
    chrom: "13",
    commonName: "Cromossomo 13",
    majorGenes: ["BRCA2", "RB1"],
    knownFor: "BRCA2 (câncer de mama/ovário) e RB1 (retinoblastoma — primeiro gene de supressão tumoral descrito).",
    notableConditions: ["Câncer mama/ovário (BRCA2)", "Retinoblastoma"],
  },
  "14": {
    chrom: "14",
    commonName: "Cromossomo 14",
    majorGenes: ["IGH", "SERPINA1", "PSEN1"],
    knownFor: "Locus da cadeia pesada de imunoglobulinas (IGH). SERPINA1 (deficiência de α1-antitripsina). PSEN1 (Alzheimer familiar).",
    notableConditions: ["Deficiência de α1-antitripsina", "Alzheimer familiar precoce"],
  },
  "15": {
    chrom: "15",
    commonName: "Cromossomo 15 — HERC2/OCA2",
    majorGenes: ["HERC2", "OCA2", "SLC24A5", "CYP1A2", "UBE3A", "FBN1"],
    knownFor: "Região HERC2/OCA2 (cor dos olhos — rs12913832). SLC24A5 (pele clara). CYP1A2 (cafeína). FBN1 (Marfan).",
    notableConditions: ["Prader-Willi / Angelman (imprinting 15q11)", "Marfan", "Albinismo tipo II"],
  },
  "16": {
    chrom: "16",
    commonName: "Cromossomo 16",
    majorGenes: ["MC1R", "ABCC11", "FTO", "VKORC1", "HBA1/HBA2"],
    knownFor: "MC1R (cabelo ruivo), ABCC11 (cera de ouvido), FTO (obesidade), VKORC1 (varfarina), cluster α-globina.",
    notableConditions: ["α-talassemia", "Rins policísticos (PKD1)"],
  },
  "17": {
    chrom: "17",
    commonName: "Cromossomo 17",
    majorGenes: ["BRCA1", "TP53", "NF1", "GFAP"],
    knownFor: "Densíssimo em genes de câncer: BRCA1, TP53, NF1.",
    notableConditions: ["Câncer de mama (BRCA1)", "Li-Fraumeni (TP53)", "Neurofibromatose 1 (NF1)"],
  },
  "18": {
    chrom: "18",
    commonName: "Cromossomo 18",
    majorGenes: ["DCC", "MC2R", "SMAD4"],
    knownFor: "Trissomia 18 (síndrome de Edwards) é a segunda mais comum viável ao nascimento após trissomia 21.",
    notableConditions: ["Síndrome de Edwards (trissomia 18)"],
  },
  "19": {
    chrom: "19",
    commonName: "Cromossomo 19 — APOE",
    majorGenes: ["APOE", "LDLR", "FUT2", "INSR"],
    knownFor: "Maior densidade gênica do genoma. APOE (Alzheimer), LDLR (hipercolesterolemia familiar), FUT2 (secretor).",
    notableConditions: ["Hipercolesterolemia familiar", "APOE ε4 (risco Alzheimer)"],
  },
  "20": {
    chrom: "20",
    commonName: "Cromossomo 20",
    majorGenes: ["GNAS", "ADA", "PRNP"],
    knownFor: "PRNP (proteína prion — doença de Creutzfeldt-Jakob). GNAS (pseudohipoparatireoidismo).",
    notableConditions: ["Prion (CJD)", "Pseudohipoparatireoidismo"],
  },
  "21": {
    chrom: "21",
    commonName: "Cromossomo 21 — o menor autossomo",
    majorGenes: ["APP", "SOD1", "DSCAM", "DYRK1A"],
    knownFor: "Menor autossomo. Trissomia 21 (síndrome de Down). APP → amiloide na trissomia, alta incidência de Alzheimer precoce em Down.",
    notableConditions: ["Síndrome de Down (trissomia 21)", "ELA familiar (SOD1)"],
  },
  "22": {
    chrom: "22",
    commonName: "Cromossomo 22",
    majorGenes: ["CYP2D6", "COMT", "TBX1", "NF2"],
    knownFor: "CYP2D6 (farmacogenômica), COMT (dopamina). Região 22q11 é hotspot de deleções (DiGeorge).",
    notableConditions: ["DiGeorge (del 22q11)", "Neurofibromatose 2"],
  },
  "X": {
    chrom: "X",
    commonName: "Cromossomo X",
    majorGenes: ["DMD", "F8", "F9", "G6PD", "FMR1", "AR"],
    knownFor: "Cromossomo sexual maior. Heranças recessivas ligadas ao X afetam homens preferencialmente: hemofilias (F8, F9), DMD, G6PD.",
    notableConditions: ["Hemofilia A/B", "Duchenne (DMD)", "X frágil (FMR1)", "Daltonismo"],
  },
  "Y": {
    chrom: "Y",
    commonName: "Cromossomo Y",
    majorGenes: ["SRY", "AMELY", "DAZ"],
    knownFor: "Cromossomo sexual masculino. SRY dispara desenvolvimento testicular. Pequeno (~60 Mb) e em degeneração evolutiva. Em chips de SNP aparece só em homens.",
    notableConditions: ["Infertilidade (deleções AZF)"],
  },
  "MT": {
    chrom: "MT",
    commonName: "DNA mitocondrial (mtDNA)",
    majorGenes: ["MT-ND1 a ND6", "MT-CO1 a CO3", "MT-CYB", "MT-RNR1/2"],
    knownFor: "Pequeno (~16.5 kb), circular, herança exclusivamente materna. Codifica 13 proteínas da cadeia respiratória + 22 tRNAs + 2 rRNAs. Mutações causam doenças mitocondriais (MELAS, LHON, MERRF). Usado em estudos de ancestralidade materna (haplogrupos).",
    notableConditions: ["LHON", "MELAS", "MERRF", "Surdez por aminoglicosídeo (MT-RNR1)"],
  },
};

export function getChromInfo(c: string): ChromosomeInfo | undefined {
  return CHROM_INFO[c];
}
